name: COLT 2020
tagline: Thirty-third Annual <br> Conference on Learning Theory
date: 9-12 July 2020
citation_date: July 2020
proceedings_title: Proceedings of the First MiniCon Conference
analytics: UA-
logo:
  image: static/images/colt2020.png
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'COLT 2020'
  separator: ': '
background_image: static/images/main.jpg
organization: Association for Computational Learning

# Remove or change to your chat server.
chat_server: miniconf.sloppy.zone
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    session: '#7cd6f7'
    coffee: '#f0ab7a'
    keynote: '#d5abff'
    business: '#ccc'
    ---: '#bed972'
  sunday_saturday: true  #  Include Sunday and Saturday
